"""empty message

Revision ID: 8c7c04e19318
Revises: b92d8b696b4b
Create Date: 2022-02-07 12:45:53.631875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8c7c04e19318"
down_revision = "b92d8b696b4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ic_d10_lookup",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=7), nullable=True),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("billable", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ic_d10_lookup")
    # ### end Alembic commands ###
