"""'JEDKH'

Revision ID: b2cf40f27613
Revises: 8c7c04e19318
Create Date: 2022-02-11 11:26:03.199580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b2cf40f27613"
down_revision = "8c7c04e19318"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opc_s4_chapter_lookup",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chapter", sa.String(length=8), nullable=True),
        sa.Column("heading", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "opc_s4_code_lookup",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=8), nullable=True),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["opc_s4_chapter_lookup.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("opc_s4_code_lookup")
    op.drop_table("opc_s4_chapter_lookup")
    # ### end Alembic commands ###
