"""'Added'

Revision ID: d3a62c0d7689
Revises: b2cf40f27613
Create Date: 2022-02-11 13:35:43.510157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3a62c0d7689"
down_revision = "b2cf40f27613"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opc_s4_sub_chapter_lookup",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subchapter", sa.String(length=8), nullable=True),
        sa.Column("heading", sa.String(length=256), nullable=True),
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["opc_s4_chapter_lookup.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subchapter"),
    )
    op.create_table(
        "opc_s4_code_lookup",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=8), nullable=True),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("subchapter_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subchapter_id"],
            ["opc_s4_sub_chapter_lookup.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_unique_constraint(None, "opc_s4_chapter_lookup", ["chapter"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "opc_s4_chapter_lookup", type_="unique")
    op.drop_table("opc_s4_code_lookup")
    op.drop_table("opc_s4_sub_chapter_lookup")
    # ### end Alembic commands ###
